# Generated by Django 6.1 on 2026-08-17 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('transport', 'Transport'), ('salaries', 'Salaries'), ('repairs', 'Repairs'), ('licences', 'Licences'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount in KES.', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description or details of the expense.')),
                ('date', models.DateField(help_text='Date the expense was incurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, help_text='Shop this expense belongs to. Null = business-wide.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='shops.shop')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
