# Generated by Django 6.1 on 2026-08-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('shop_manager', 'Shop Manager'), ('cashier', 'Cashier')], default='cashier', help_text="Determines the user's access level in the system.", max_length=20),
        ),
    ]
