# Generated by Django 6.1 on 2026-08-17 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier / vendor name.', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Supplier contact phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Supplier contact email.', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Supplier physical address.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive suppliers are hidden from receiving forms.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, help_text='Delivery note or invoice reference number.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the stock was received.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receives', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receives', to='shops.shop')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier for this delivery. Optional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_receives', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'stock receive',
                'verbose_name_plural': 'stock receives',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity received.')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Buying price per unit at time of receiving (KES).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receive_items', to='products.product')),
                ('stock_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreceive')),
            ],
            options={
                'verbose_name': 'stock receive item',
                'verbose_name_plural': 'stock receive items',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('received', 'Stock Received'), ('sold', 'Sold'), ('damaged', 'Damaged'), ('written_off', 'Written Off'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Signed quantity: positive for in, negative for out.')),
                ('balance_after', models.IntegerField(help_text='Stock balance after this movement.')),
                ('reference', models.CharField(blank=True, help_text='Reference number (receipt, invoice, delivery note).', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reason for the movement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='shops.shop')),
            ],
            options={
                'verbose_name': 'inventory movement',
                'verbose_name_plural': 'inventory movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'product', '-created_at'], name='idx_movement_shop_product_date')],
            },
        ),
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity. May be negative in edge cases.')),
                ('minimum_stock_level', models.PositiveIntegerField(blank=True, help_text='Shop-specific minimum stock threshold. If null, the product-level default is used.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product being tracked.', on_delete=django.db.models.deletion.PROTECT, related_name='shop_inventory_records', to='products.product')),
                ('shop', models.ForeignKey(help_text='The shop holding this inventory.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='shops.shop')),
            ],
            options={
                'verbose_name': 'shop inventory',
                'verbose_name_plural': 'shop inventories',
                'ordering': ['shop__name', 'product__name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'product'), name='unique_shop_product_inventory')],
            },
        ),
    ]
