# Generated by Django 6.0.3 on 2026-08-17 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_product_product_buying_price_non_negative_and_more'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='inventory_movement_balance_after_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='shopinventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='shop_inventory_quantity_non_negative'),
        ),
    ]
