# Generated by Django 6.1 on 2026-08-17 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shop display name.', max_length=100, unique=True)),
                ('location', models.CharField(help_text='Physical address or location description.', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Shop contact phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Shop contact email address.', max_length=254)),
                ('licence_number', models.CharField(blank=True, help_text='Liquor licence number.', max_length=50)),
                ('licence_expiry', models.DateField(blank=True, help_text='Liquor licence expiry date.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive shops are hidden from operational views.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive assignments are treated as revoked.')),
                ('shop', models.ForeignKey(help_text='The shop the user is assigned to.', on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='shops.shop')),
                ('user', models.ForeignKey(help_text='The user assigned to the shop.', on_delete=django.db.models.deletion.PROTECT, related_name='shop_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shop assignment',
                'verbose_name_plural': 'shop assignments',
                'ordering': ['shop__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_assignment')],
            },
        ),
    ]
