# Generated by Django 6.1 on 2026-08-17 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, help_text='Unique sale/receipt number.', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Pre-tax total in KES.', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount in KES.', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final total including tax in KES.', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Optional notes (e.g., reason for void).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='shops.shop')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in KES.', max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference (M-Pesa code, card ref, etc.).', max_length=100)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, help_text='Amount tendered (for cash change calculation).', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at the time of sale.', max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity sold.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit at time of sale (KES).', max_digits=10)),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit at time of sale (KES).', max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax rate at time of sale (percentage).', max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price (KES).', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'sale item',
                'verbose_name_plural': 'sale items',
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop', '-created_at'], name='idx_sale_shop_date'),
        ),
    ]
