# Generated by Django 6.1 on 2026-08-17 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Whisky, Wine, Vodka, Beer).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from product forms.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product display name.', max_length=200)),
                ('brand', models.CharField(blank=True, help_text='Brand or manufacturer name.', max_length=100)),
                ('sku', models.CharField(db_index=True, help_text='Unique product code / Stock Keeping Unit.', max_length=50, unique=True, verbose_name='SKU')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Default buying/cost price in KES.', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Default selling price in KES.', max_digits=10)),
                ('unit_of_measurement', models.CharField(choices=[('bottle', 'Bottle'), ('can', 'Can'), ('case', 'Case'), ('keg', 'Keg'), ('pack', 'Pack'), ('piece', 'Piece'), ('other', 'Other')], default='bottle', help_text='Unit used for stock counting.', max_length=20)),
                ('minimum_stock_level', models.PositiveIntegerField(default=0, help_text='System-wide minimum stock threshold. Shops can override.')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax/excise rate as a percentage (e.g., 16.00 for 16%).', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive/discontinued products are hidden from POS.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
    ]
