# Generated by Django 6.0.3 on 2026-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('buying_price__gte', 0)), name='product_buying_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='product_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='product_tax_rate_non_negative'),
        ),
    ]
